### ISSUE TITLE
issues with worldgen in an infinite height

### ISSUE THREAD

**Issue by Redd56** [hm-ysjiang/usefulstuff#2]
when cubic chunks is installed this mod has issues with its worldgen. specificly it hangs for some reason. Someone who knows way more about this stuff (specificly barteks2x dev of cubic chunks) said something about getHeight being used in exactly the places that it breaks cc, and that using hard code values where using getHeight would help.. how it would idk....  maybe im missinterpiting... but none the less it just freezes worldgen

**Comment by hm-ysjiang** [comment]
Yeah, that makes sense. The bush generator looks for the ground y by searching from the top of the world, and of course it freezes if the ceiling is super high. I will push a new version with the fix later.

And thanks for reporting BTW.

**Comment by Redd56** [comment]
Yw
