### ISSUE TITLE
Universal Core recipe doesnt work because of missing oredict entry itemSkull

### ISSUE THREAD

**Issue by Corosauce** [hm-ysjiang/usefulstuff#5]
I guess you are running your mod with other mods or didnt quite check, because plain vanilla setup doesnt have itemSkull oredict'd by default.

You can fix by registering the oredict yourself that other mods like Woot or EnderIO also do, should be safe to just blindly add it like EnderIO does: https://github.com/SleepyTrousers/EnderIO/blob/66dce888cabb1d024f255ad77bd9c1f3bb0ba642/enderio-base/src/main/java/crazypants/enderio/base/material/recipes/MaterialOredicts.java#L98-L99

In the meantime I used unidict to manually register the itemSkull oredict for all skull metas.

**Comment by hm-ysjiang** [comment]
:scream:
Thank you for reporting!
