### ISSUE TITLE
Dye Bushes aren't solid.

### ISSUE THREAD

**Issue by Scratchman** [hm-ysjiang/usefulstuff#6]
I'd like to use the dye bushes as a colourful hedge as well as a way to obtain berries for dyes, but because the dye bushes don't have hitboxes, animals and mobs can pass through them.

Could you please add hitboxes to the bushes?

Thanks for the time and effort you've put into your mod.

**Comment by hm-ysjiang** [comment]
Uhh, I intended to make the bushes passable...

How about a config option that makes the bushes solid?

**Comment by Scratchman** [comment]
That would be awesome. Thank you. 👍
